prSections:
    - title: My Pull Requests
      filters: is:open author:@me
    - title: Needs My Review
      filters: is:open review-requested:@me
    - title: Involved
      filters: is:open involves:@me -author:@me
issuesSections:
    - title: My Issues
      filters: is:open author:@me
    - title: Assigned
      filters: is:open assignee:@me
    - title: Involved
      filters: is:open involves:@me -author:@me
repo:
    branchesRefetchIntervalSeconds: 30
    prsRefetchIntervalSeconds: 60
defaults:
    preview:
        open: true
        width: 50
    prsLimit: 20
    prApproveComment: LGTM
    issuesLimit: 20
    view: prs
    layout:
        prs:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 20
            author:
                width: 15
            authorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
            base:
                width: 15
                hidden: true
            lines:
                width: 15
        issues:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 15
            creator:
                width: 10
            creatorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
    refetchIntervalMinutes: 30
keybindings: {}
repoPaths: {}
pager:
    diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
theme:
  ui:
    table:
      showSeparator: true
  colors:
    text:
      primary: "#f8f8f2"
      secondary: "#ff79c6"
      inverted: "#282a36"
      faint: "#ffb86c"
      warning: "#ff5555"
      success: "#50fa7b"
    background:
      selected: "#AD85FC"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
